version: '3.5'

services:

  server:
    image: venom_api:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: venom_api
    depends_on:
      - mongo
    ports:
      - 4000:4000
    environment:
      MONGO_URL: mongodb://venom:venom@mongo:27017/venom

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./init-db/init-mongo.sh:/docker-entrypoint-