@apiPrefix = /api/v1
@port = 4000
@host = localhost
@baseUrl = http://{{host}}:{{port}}{{apiPrefix}}

@currenciesPath = {{baseUrl}}/currencies

###
GET {{currenciesPath}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImNyeXB0by1tY